import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
  const val appcompat: String = "1.4.0"

  const val constraintlayout: String = "2.1.2"

  const val core_ktx: String = "1.7.0"

  const val androidx_navigation: String = "2.3.5"

  const val espresso_core: String = "3.4.0"

  const val androidx_test_ext_junit: String = "1.1.3"

  const val aapt2: String = "7.0.3-7396180" // available: "7.0.3-7396180"

  const val com_android_tools_build_gradle: String = "7.0.3" // available: "7.0.3"

  const val lint_gradle: String = "30.0.3" // available: "30.0.3"

  const val material: String = "1.4.0"

  const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0" // available: "0.7.0"

  const val junit_junit: String = "4.13.2"

  const val dokka_gradle_plugin: String = "1.6.0" // available: "1.6.0"

  const val org_jetbrains_kotlin: String = "1.6.0" // available: "1.6.0"

  const val kotlinx_coroutines_android: String = "1.5.2"

  const val org_reduxkotlin: String = "0.5.5"

  /**
   *
   * See issue 19: How to update Gradle itself?
   * https://github.com/jmfayard/buildSrcVersions/issues/19
   */
  const val gradleLatestVersion: String = "7.3"

  const val gradleCurrentVersion: String = "6.6"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
  inline get() =
      id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
