name: Publish snapshot

on:
  push:
    branches: [ master, feature/*, kotlin-* ]
  pull_request:
    branches: [ master ]

jobs:
  publish-snapshot:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
        # build release artifacts source and Javadoc jars + publish the artifacts
    - name: Publish macOS artifacts
      id: publish-macos
      if: matrix.os == 'macos-latest'
      run: ./gradlew
        -PossUsername=${{ secrets.OSSRH_USERNAME }}
        -PossPassword=${{ secrets.OSSRH_PASSWORD }}
        -PsigningKeyId=${{ secrets.SIGNINGKEYID }}
        -PsigningKeyPassword="${{ secrets.SIGNINGKEYPASSWORD }}"
        -PsigningKey="${{ secrets.SIGNINGKEY }}"
        publish

    - name: Publish windows artifacts snapshot
      id: publish-win
      if: matrix.os == 'windows-latest'
      run: ./gradlew
        -PossUsername=${{ secrets.OSSRH_USERNAME }}
        -PossPassword=${{ secrets.OSSRH_PASSWORD }}
        -PsigningKeyId=${{ secrets.SIGNINGKEYID }}
        -PsigningKeyPassword="${{ secrets.SIGNINGKEYPASSWORD }}"
        -PsigningKey="${{ secrets.SIGNINGKEY }}"
        publish

    - name: Publish linux artifacts snapshot
      id: publish-linux
      if: matrix.os == 'ubuntu-latest'
      run: ./gradlew
        -PossUsername=${{ secrets.OSSRH_USERNAME }}
        -PossPassword=${{ secrets.OSSRH_PASSWORD }}
        -PsigningKeyId=${{ secrets.SIGNINGKEYID }}
        -PsigningKeyPassword="${{ secrets.SIGNINGKEYPASSWORD }}"
        -PsigningKey="${{ secrets.SIGNINGKEY }}"
        publish

    - name: Archive publications dir
      uses: actions/upload-artifact@v1
      with:
        name: publications-${{ matrix.os }}
        path: select/build/publications
