name: Publish a release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Publish Release
      env:
        ossUsername: ${{ secrets.OSSRH_USERNAME }}
        ossPassword: ${{ secrets.OSSRH_PASSWORD }}
        signingKeyId: ${{ secrets.SIGNINGKEYID }}
        signingKeyPassword: ${{ secrets.SIGNINGKEYPASSWORD }}
        signingKey: ${{ secrets.SIGNINGKEY }}
      run: ./gradlew publish
