name: Publish a release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Publish Release
      run: ./gradlew
        -PossUsername=${{ secrets.OSSRH_USERNAME }}
        -PossPassword=${{ secrets.OSSRH_PASSWORD }}
        -PsigningKeyId=${{ secrets.SIGNINGKEYID }}
        -PsigningKeyPassword="${{ secrets.SIGNINGKEYPASSWORD }}"
        -PsigningKey="${{ secrets.SIGNINGKEY }}"
        publish
