name: Publish snapshot

on:
  push:
    branches: [ master, feature/*, kotlin-* ]
  pull_request:
    branches: [ master ]

jobs:
  publish-snapshot:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Publish macOS artifacts snapshot
      id: publish-macos
      if: matrix.os == 'macos-latest'
      env:
        ossUsername: ${{ secrets.OSSRH_USERNAME }}
        ossPassword: ${{ secrets.OSSRH_PASSWORD }}
        signingKeyId: ${{ secrets.SIGNINGKEYID }}
        signingKeyPassword: ${{ secrets.SIGNINGKEYPASSWORD }}
        signingKey: ${{ secrets.SIGNINGKEY }}
        SNAPSHOT: 'TRUE'
      run: ./gradlew publish

    - name: Publish windows artifacts snapshot
      id: publish-win
      if: matrix.os == 'windows-latest'
      env:
        ossUsername: ${{ secrets.OSSRH_USERNAME }}
        ossPassword: ${{ secrets.OSSRH_PASSWORD }}
        signingKeyId: ${{ secrets.SIGNINGKEYID }}
        signingKeyPassword: ${{ secrets.SIGNINGKEYPASSWORD }}
        signingKey: ${{ secrets.SIGNINGKEY }}
        SNAPSHOT: 'TRUE'
      run: ./gradlew publish

    - name: Publish linux artifacts snapshot
      id: publish-linux
      if: matrix.os == 'ubuntu-latest'
      env:
        ossUsername: ${{ secrets.OSSRH_USERNAME }}
        ossPassword: ${{ secrets.OSSRH_PASSWORD }}
        signingKeyId: ${{ secrets.SIGNINGKEYID }}
        signingKeyPassword: ${{ secrets.SIGNINGKEYPASSWORD }}
        signingKey: ${{ secrets.SIGNINGKEY }}
        SNAPSHOT: 'TRUE'
      run: ./gradlew publish

    - name: Archive publications dir
      uses: actions/upload-artifact@v1
      with:
        name: publications-${{ matrix.os }}
        path: select/build/publications
